version: "3"

services:
  php:
    image: sugenk/php5.6-fpm-alpine:arm64
    volumes:
      - /src/:/var/www/html
  nginx:
    image: nginx:latest
    ports:
      - "25680:80"
    volumes:
      - /home/ubuntu/docker-test/src/:/var/www/html
      - /home/ubuntu/docker-test/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
